const types = {
  FETCH_TRIP_FILTERS: "trips/fetchTripFilters",
  FETCH_TRIP_FILTERS_SUCCESS: "FETCH_TRIP_FILTERS_SUCCESS",
  FETCH_TRIP_FILTERS_FAILURE: "FETCH_TRIP_FILTERS_FAILURE",
  APPLY_FILTER: "TRIPS/APPLY_FILTER",

  FETCH_OPERATOR_TRIPS_START: "trips/fetchTrips",
  CLEAR_OPERATOR_TRIPS: "CLEAR_OPERATOR_TRIPS",
};

export default types;
